-- Script para adicionar tabela de escolas e campo na tabela de inscrições
-- Execute este script no Supabase SQL Editor

-- 1. Criar tabela de escolas
CREATE TABLE IF NOT EXISTS escolas (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('Municipal', 'Estadual', 'Federal', 'Particular')),
  cidade TEXT DEFAULT 'Imperatriz',
  estado TEXT DEFAULT 'MA',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Adicionar índice para busca por nome
CREATE INDEX IF NOT EXISTS idx_escolas_nome ON escolas USING GIN (to_tsvector('portuguese', nome));
CREATE INDEX IF NOT EXISTS idx_escolas_tipo ON escolas (tipo);

-- 3. Inserir dados das escolas de Imperatriz-MA
INSERT INTO escolas (nome, tipo) VALUES
('Colégio Estadual Inf Professora Juracy Athayde Conceicao', 'Municipal'),
('Colégio Estadual Maranhense', 'Municipal'),
('Centro de Ensino Amaral Raposo', 'Estadual'),
('Centro de Ensino de Educação de Jovens e Adultos II', 'Estadual'),
('Centro de Ensino Delahe Fiquene', 'Estadual'),
('Centro de Ensino Dorgival Pinheiro de Sousa', 'Estadual'),
('Centro de Ensino Dorgival Pinheiro de Sousa - Anexo I - Centro', 'Estadual'),
('Centro de Ensino Dorgival Pinheiro de Sousa - Anexo II - Petrolina', 'Estadual'),
('Centro de Ensino Estado de Goias', 'Estadual'),
('Centro de Ensino Governador Archer', 'Estadual'),
('Centro de Ensino Graca Aranha', 'Estadual'),
('Centro de Ensino Nova Vitoria', 'Estadual'),
('Centro de Ensino Professor Edinan Moraes', 'Estadual'),
('Centro de Ensino Raimundo Soares da Cunha', 'Estadual'),
('Centro de Ensino Uniao', 'Estadual'),
('Centro de Ensino Urbano Rocha', 'Estadual'),
('Centro de Ensino Vespasiano Ramos', 'Estadual'),
('Centro de Ensino Vinicius de Moraes', 'Estadual'),
('Centro Educa Mais Caminho do Futuro', 'Estadual'),
('Centro Educa Mais Mourao Rangel', 'Estadual'),
('Centro Educa Mais Nascimento de Moraes', 'Estadual'),
('Centro Educa Mais Tancredo de Almeida Neves', 'Estadual'),
('Colégio Militar Tiradentes II - Imperatriz', 'Estadual'),
('Conselho Comunitario do Pq Alvorada Dois', 'Municipal'),
('Creche Aconchego', 'Municipal'),
('Creche Cantinho do Saber', 'Municipal'),
('Creche Cidade Esperanca', 'Municipal'),
('Creche Moranguinho', 'Municipal'),
('Creche Municipal Arco Iris', 'Municipal'),
('Creche Municipal Caminho Feliz', 'Municipal'),
('Creche Municipal Cirandinha', 'Municipal'),
('Creche Municipal Irma Dulce', 'Municipal'),
('Creche Municipal Cantinho da Alegria I', 'Municipal'),
('Creche Municipal Antonia Glaucimeire', 'Municipal'),
('Creche Municipal Educandario do Saber', 'Municipal'),
('Creche Municipal Mundo Infantil', 'Municipal'),
('Creche Municipal Santa Margarida', 'Municipal'),
('Creche Municipalizada Maranhao do Sul', 'Municipal'),
('Creche Risco e Rabisco', 'Municipal'),
('Creche Santa Terezinha', 'Municipal'),
('Creche Vovo Suelly', 'Municipal'),
('Educandario Lirio dos Vales', 'Municipal'),
('Escola Municipal Afonso Pena', 'Municipal'),
('Escola Municipal Bernardo Sayao', 'Municipal'),
('Escola Municipal Casa de Dom Bosco', 'Municipal'),
('Escola Municipal Castro Alves II', 'Municipal'),
('Escola Municipal Chaparral', 'Municipal'),
('Escola Municipal Coelho Neto', 'Municipal'),
('Escola Municipal Creche Esperanca', 'Municipal'),
('Escola Municipal da Amizade', 'Municipal'),
('Escola Municipal Darcy Ribeiro', 'Municipal'),
('Escola Municipal de 1 Grau Princesa Izabel', 'Municipal'),
('Escola Municipal de Educação Infantil Frei Benjamin Zanardini', 'Municipal'),
('Escola Municipal de Educação Infantil Governador Jackson Lago', 'Municipal'),
('Escola Municipal de Educação Infantil Jair Rosignoli', 'Municipal'),
('Escola Municipal de Educação Infantil José Ribamar Garros', 'Municipal'),
('Escola Municipal de Educação Infantil Maria José Silva Nunes', 'Municipal'),
('Escola Municipal de Ensino Fundamental Ipiranga', 'Municipal'),
('Escola Municipal Dom Marcelino', 'Municipal'),
('Escola Municipal Dom Pedro I', 'Municipal'),
('Escola Municipal Educ Bilingue Para Surdos Professor Telasco Pereira Filho', 'Municipal'),
('Escola Municipal Enock Alves Bezerra', 'Municipal'),
('Escola Municipal Fraternidade', 'Municipal'),
('Escola Municipal Frei Manoel Procopio', 'Municipal'),
('Escola Municipal Frei Tadeu', 'Municipal'),
('Escola Municipal Giovanni Zanni', 'Municipal'),
('Escola Municipal Humberto de Campos', 'Municipal'),
('Escola Municipal João Goncalves Santiago', 'Municipal'),
('Escola Municipal João Guimaraes', 'Municipal'),
('Escola Municipal João Lisboa', 'Municipal'),
('Escola Municipal José de Alencar', 'Municipal'),
('Escola Municipal Juscelino Kubitschek', 'Municipal'),
('Escola Municipal Lago do Cisne', 'Municipal'),
('Escola Municipal Lauro Tupinamba Valente', 'Municipal'),
('Escola Municipal Leoncio Pires Dourado', 'Municipal'),
('Escola Municipal Luis de Franca Moreira', 'Municipal'),
('Escola Municipal Machado de Assis', 'Municipal'),
('Escola Municipal Madalena de Canossa', 'Municipal'),
('Escola Municipal Manoel Ribeiro', 'Municipal'),
('Escola Municipal Marcionilia Gomes Soares', 'Municipal'),
('Escola Municipal Marechal Rondon', 'Municipal'),
('Escola Municipal Maria das Neves Marques de Sousa', 'Municipal'),
('Escola Municipal Mariana Luz', 'Municipal'),
('Escola Municipal Marly Sarney', 'Municipal'),
('Escola Municipal Menino Jesus II', 'Municipal'),
('Escola Municipal Moranguinho', 'Municipal'),
('Escola Municipal Moreira Neto', 'Municipal'),
('Escola Municipal Nossa Senhora de Nazare', 'Municipal'),
('Escola Municipal Nucleo Santa Cruz', 'Municipal'),
('Escola Municipal Paulo Freire', 'Municipal'),
('Escola Municipal Pedro Abreu', 'Municipal'),
('Escola Municipal Pres Costa e Silva', 'Municipal'),
('Escola Municipal Professor José Queiroz', 'Municipal'),
('Escola Municipal Raimundo Correa', 'Municipal'),
('Escola Municipal Raimundo Ribeiro', 'Municipal'),
('Escola Municipal Santa Clara de Assis - Jisca', 'Municipal'),
('Escola Municipal Santa Laura', 'Municipal'),
('Escola Municipal Santa Lucia', 'Municipal'),
('Escola Municipal Santa Maria', 'Municipal'),
('Escola Municipal Santa Rita', 'Municipal'),
('Escola Municipal Santa Tereza', 'Municipal'),
('Escola Municipal Santa Tereza D Avila', 'Municipal'),
('Escola Municipal Santo Amaro', 'Municipal'),
('Escola Municipal Santo Inacio de Loyola', 'Municipal'),
('Escola Municipal Santos Dumont', 'Municipal'),
('Escola Municipal São Felix', 'Municipal'),
('Escola Municipal São Francisco', 'Municipal'),
('Escola Municipal São Francisco do Caninde', 'Municipal'),
('Escola Municipal São Jorge I', 'Municipal'),
('Escola Municipal São Sebastiao', 'Municipal'),
('Escola Municipal São Vicente de Paula', 'Municipal'),
('Escola Municipal Senhor Jesus', 'Municipal'),
('Escola Municipal Sousa Lima', 'Municipal'),
('Escola Municipal Tia Emilia', 'Municipal'),
('Escola Municipal Tocantins', 'Municipal'),
('Escola Municipal Tome de Sousa', 'Municipal'),
('Escola Municipal Vital Brazil', 'Municipal'),
('Escola Municipal Wady Fiquene', 'Municipal'),
('Escola Municipal de Educação Infantil Nossa Senhora de Fatima', 'Municipal'),
('Escola Municipal de Educação Infantil Shirley Farias Torres Ferreira', 'Municipal'),
('Escola Municipalizada Frei Paulo de Graymoor', 'Municipal'),
('Escola Espaço Infantil Maranatha', 'Municipal'),
('Escola Municipal de Educação Infantil Maria Luiza Coelho Brandao', 'Municipal'),
('Escola Municipal Adalberto Franklin Pereira de Castro', 'Municipal'),
('Escola Municipal Antonio Leite Andrade', 'Municipal'),
('Escola Municipal Castro Alves I', 'Municipal'),
('Escola Municipal Constantino Barbosa da Silva', 'Municipal'),
('Escola Municipal de Educação Infantil Herica Barros de Jesus', 'Municipal'),
('Escola Municipal de Educação Infantil Jeova Pereira da Silva', 'Municipal'),
('Escola Municipal de Educação Infantil José Carneiro dos Santos', 'Municipal'),
('Escola Municipal de Educação Infantil Marlene Soares', 'Municipal'),
('Escola Municipal de Educação Infantil Pequeno Principe', 'Municipal'),
('Escola Municipal de Ensino Fundamental Goncalves Dias', 'Municipal'),
('Escola Municipal Domingos Moraes', 'Municipal'),
('Escola Municipal Edelvira Marques', 'Municipal'),
('Escola Municipal Eliza Nunes', 'Municipal'),
('Escola Municipal Fernanda Branco Oliveira', 'Municipal'),
('Escola Municipal João Silva', 'Municipal'),
('Escola Municipal Maria Evangelista de Sousa', 'Municipal'),
('Escola Municipal Maria Francisca Pereira da Silva', 'Municipal'),
('Escola Municipal Morada do Sol', 'Municipal'),
('Escola Municipal Nossa Senhora da Conceicao', 'Municipal'),
('Escola Municipal Pedro Ferreira Alencar', 'Municipal'),
('Escola Municipal Sumare', 'Municipal'),
('Escola Municipal Tiradentes II', 'Municipal'),
('Fundacao Educacional Pirangi', 'Municipal'),
('Iema - Instituto Estadual de Educação Ciencia e Tecnologia do MA - Unidade Vocacional Imperatriz', 'Estadual'),
('Instituto Estadual de Educação Ciencia e Tecnologia do Maranhao - Iema Pleno Imperatriz', 'Estadual');

-- 4. Adicionar campo escola na tabela de inscrições
ALTER TABLE inscricoes 
ADD COLUMN IF NOT EXISTS escola TEXT;

-- 5. Comentário sobre o campo escola
COMMENT ON COLUMN inscricoes.escola IS 'Nome da escola onde a aluna estuda';

-- 6. Criar política de segurança para a tabela escolas (permitir leitura pública)
ALTER TABLE escolas ENABLE ROW LEVEL SECURITY;

-- Remover política existente se houver e criar nova
DROP POLICY IF EXISTS "Enable read access for all users" ON escolas;
CREATE POLICY "Enable read access for all users" ON escolas
FOR SELECT USING (true);

-- 7. Garantir que a tabela escolas seja acessível via API do Supabase
GRANT SELECT ON escolas TO anon;
GRANT SELECT ON escolas TO authenticated;
